# Generated by Django 4.0.4 on 2022-07-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated',
            field=models.CharField(max_length=100),
        ),
    ]
