# Generated by Django 4.0.4 on 2022-05-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='vote',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
