# Generated by Django 4.0.4 on 2022-06-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_question_n_answers_question_n_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
